[project]
name = "gemini-balance"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
<<<<<<< Updated upstream
requires-python = ">=3.12"
dependencies = [
    "aiomysql>=0.2.0",
    "aiosqlite>=0.21.0",
    "apscheduler>=3.11.0",
    "cryptography>=45.0.5",
    "databases>=0.9.0",
    "fastapi>=0.115.14",
    "google-genai>=1.24.0",
    "httpx[socks]>=0.28.1",
    "jinja2>=3.1.6",
    "openai>=1.93.0",
    "packaging>=25.0",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "pymysql>=1.1.1",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.20",
    "requests>=2.32.4",
    "sqlalchemy>=2.0.41",
    "starlette>=0.46.2",
    "uvicorn>=0.35.0",
=======
requires-python = ">=3.11"
dependencies = [
    "aiomysql>=0.3.2",
    "aiosqlite>=0.21.0",
    "apscheduler>=3.11.0",
    "cryptography>=46.0.3",
    "databases>=0.9.0",
    "fastapi>=0.119.1",
    "google-genai>=1.46.0",
    "httpx[socks]>=0.28.1",
    "jinja2>=3.1.6",
    "openai>=2.6.0",
    "packaging>=25.0",
    "pydantic>=2.12.3",
    "pydantic-settings>=2.11.0",
    "pymysql>=1.1.2",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.20",
    "requests>=2.32.5",
    "sqlalchemy>=2.0.44",
    "starlette>=0.48.0",
    "uvicorn>=0.38.0",
>>>>>>> Stashed changes
]
